/**
 * Athena — The Configurator
 * interview-data.js — Tier 1 + Tier 2 interview screen definitions
 * Version: 0.3.1.1
 * Copyright 2026 by Alan H. Jordan | All Rights Reserved | Digital and Otherwise
 */

// ─── Tier 1 Interview Screens ──────────────────────────────────────
window.INTERVIEW_SCREENS = [
  {
    id: 'welcome',
    type: 'info',
    title: 'Welcome',
    body: "I'm Athena, and I'm here to learn from you. Over the next few minutes, I'll ask about your expertise — the problems you solve and how you solve them. There are no wrong answers. Just share what you know, and I'll organize it.",
    psiField: null,
  },
  {
    id: 'name',
    type: 'text',
    title: "What's your name?",
    subtitle: "First and last, however you'd like people to know you.",
    placeholder: 'e.g., Dr. Sarah Chen, Coach Mike Davis',
    psiField: 'name',
    required: true,
    maxLength: 120,
  },
  {
    id: 'practice',
    type: 'text',
    title: 'What is the name of your practice or organization?',
    subtitle: "If you're independent, your own name works fine.",
    placeholder: 'e.g., Summit Physical Therapy, Jordan Wellness',
    psiField: 'practice',
    required: false,
    maxLength: 200,
  },
  {
    id: 'whatYouDo',
    type: 'textarea',
    title: 'In a sentence or two, what do you do?',
    subtitle: "Tell me the way you'd tell a friend, not a résumé.",
    placeholder: 'e.g., I help runners recover from foot injuries and get back on the road.',
    psiField: 'whatYouDo',
    required: true,
    maxLength: 500,
  },
  {
    id: 'domain',
    type: 'text',
    title: 'What would you call your field or specialty?',
    subtitle: 'Two or three words that describe your area of expertise.',
    placeholder: 'e.g., urology, B2B sales coaching, orthopedic footwear, computer repair',
    psiField: 'domain',
    required: true,
    maxLength: 150,
  },
  {
    id: 'audience',
    type: 'textarea',
    title: 'Who are the people you help?',
    subtitle: 'Describe your typical client, patient, or audience.',
    placeholder: 'e.g., Weekend athletes over 40 dealing with chronic foot pain.',
    psiField: 'audience',
    required: true,
    maxLength: 500,
  },
  {
    id: 'frequency',
    type: 'text',
    title: 'How often do you typically see or interact with them?',
    subtitle: 'This helps me understand your workflow.',
    placeholder: 'e.g., weekly visits, monthly check-ins, as-needed',
    psiField: 'frequency',
    required: false,
    maxLength: 150,
  },
  {
    id: 'situations',
    type: 'multiItem',
    title: 'What situations do your people bring to you most often?',
    subtitle: "Use an action phrase followed by a condition \u2014 for example, \u2018obtain relief from Sciatica\u2019 or \u2018eliminate Shoulder pain\u2019. Add one per box.",
    placeholder: 'e.g., obtain relief from Sciatica',
    addLabel: '+ Add another situation',
    hint: '\uD83D\uDCA1 One situation per box. Use a verb phrase like \u201Cobtain relief from\u201D or \u201Celiminate\u201D followed by the condition.',
    psiField: 'situations',
    required: true,
    minItems: 1,
    maxItems: 20,
    maxLength: 300,
  },
  {
    id: 'notes',
    type: 'textarea',
    title: 'Anything else I should know?',
    subtitle: "Context, caveats, things that don't fit the other questions. Optional.",
    placeholder: 'e.g., I also handle referrals from podiatrists, most patients are post-surgical…',
    psiField: 'notes',
    required: false,
    maxLength: 1000,
  },
  {
    id: 'review',
    type: 'review',
    title: "Here's what I've gathered so far",
    subtitle: 'Review everything below. You can go back to change anything before we continue.',
    psiField: null,
  },
];

// ─── Tier 2 Interview Screens (per-situation drill-down) ───────────
window.TIER2_SCREENS = [
  {
    id: 'whatToTell',
    type: 'textarea',
    title: 'What do you tell them when this happens?',
    subtitle: "Your first piece of guidance — what you'd say face to face.",
    placeholder: 'e.g., The first thing I tell them is to ice the area for 20 minutes…',
    psiField: 'initialGuidance',
    required: true,
    maxLength: 1000,
  },
  {
    id: 'makesWorse',
    type: 'textarea',
    title: 'What makes it worse?',
    subtitle: 'Triggers, bad habits, things to avoid.',
    placeholder: 'e.g., Wearing unsupportive shoes, ignoring early symptoms…',
    psiField: 'contraindications',
    required: false,
    maxLength: 1000,
  },
  {
    id: 'firstStep',
    type: 'textarea',
    title: "What's the first step they should take?",
    subtitle: 'The single most important action.',
    placeholder: 'e.g., Schedule an assessment appointment within the week.',
    psiField: 'firstStep',
    required: true,
    maxLength: 500,
  },
  {
    id: 'alreadyTried',
    type: 'textarea',
    title: "What if they've already tried that?",
    subtitle: 'Second-line advice, alternatives, next steps.',
    placeholder: 'e.g., If stretching hasn\'t helped after two weeks, we move to custom orthotics…',
    psiField: 'alternatives',
    required: false,
    maxLength: 1000,
  },
  {
    id: 'resources',
    type: 'textarea',
    title: 'Is there a resource you\'d point them to?',
    subtitle: 'A website, a handout, a video — anything they can reference on their own.',
    placeholder: 'e.g., Our stretching guide PDF, the AAOS patient education page…',
    psiField: 'resources',
    required: false,
    maxLength: 500,
  },
  {
    id: 'escalation',
    type: 'textarea',
    title: 'When should they contact you instead of handling it themselves?',
    subtitle: 'Red flags, thresholds, urgent signals.',
    placeholder: 'e.g., If pain is above 7/10, if swelling doesn\'t go down in 48 hours…',
    psiField: 'escalation',
    required: true,
    maxLength: 500,
  },
];

// ─── Credential Fields ─────────────────────────────────────────────
window.CREDENTIAL_FIELDS = [
  {
    id: 'licenseType',
    type: 'text',
    label: 'License or certification type',
    placeholder: 'e.g., DPM, MD, RN, CSCS, CPA',
    required: false,
    maxLength: 100,
  },
  {
    id: 'licenseNumber',
    type: 'text',
    label: 'License or ID number',
    placeholder: 'e.g., NPI number, state license number, or enter "prefer not to share"',
    required: false,
    maxLength: 100,
  },
  {
    id: 'issuingBody',
    type: 'text',
    label: 'Issued by',
    placeholder: 'e.g., State of Nevada Board of Medical Examiners',
    required: false,
    maxLength: 200,
  },
  {
    id: 'professionalUrl',
    type: 'text',
    label: 'Professional website or LinkedIn',
    placeholder: 'e.g., https://www.yourpractice.com',
    required: false,
    maxLength: 300,
  },
  {
    id: 'yearsExperience',
    type: 'text',
    label: 'Years of experience in this field',
    placeholder: 'e.g., 12',
    required: false,
    maxLength: 10,
  },
];
